name: scenicorg.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39078
title: 'Scenic Home & Office Organizers'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64900635-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#98e7e8'
    - '#ffcf55'
    - '#ddf7f7'
    - '#ffeab4'
  brandStrength: 0.0625
  lightness: 0.035631103441119194
  saturation: 0.06352492445148528
  rhythmicContrast: 0.7536380358505994
purpose: []
